# Generated by Django 5.2.1 on 2025-07-03 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JubJubWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=50, unique=True)),
                ("syllables", models.CharField(blank=True, max_length=100)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("markov_order", models.IntegerField(blank=True, null=True)),
                ("syllable_awareness", models.FloatField(blank=True, null=True)),
                ("copy_count", models.IntegerField(default=0)),
                ("definition_count", models.IntegerField(default=0)),
                (
                    "first_generated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_shown", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-copy_count", "-definition_count"],
            },
        ),
        migrations.CreateModel(
            name="WordDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="jubjubword.jubjubword",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("copy", "Copied Word"),
                            ("define", "Added Definition"),
                            ("upvote", "Upvoted Definition"),
                            ("downvote", "Downvoted Definition"),
                            ("generate", "Generated Word"),
                            ("shown", "Shown Community Word"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jubjubword.worddefinition",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="jubjubword.jubjubword",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="jubjubword__session_1236f5_idx",
                    ),
                    models.Index(
                        fields=["word", "interaction_type"],
                        name="jubjubword__word_id_951cd6_idx",
                    ),
                ],
                "unique_together": {("session_id", "definition", "interaction_type")},
            },
        ),
    ]
