# Generated by Django 5.2.1 on 2025-07-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jubjubword", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("theme_color", models.CharField(default="#3A2449", max_length=7)),
                ("icon_emoji", models.CharField(default="🦜", max_length=10)),
                ("words", models.TextField(help_text="One word per line")),
                ("word_count", models.IntegerField(default=0, editable=False)),
                ("times_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Corpora",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="jubjubword",
            name="corpus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_words",
                to="jubjubword.corpus",
            ),
        ),
    ]
