# Generated by Django 5.2.1 on 2025-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jubjubword", "0002_corpus_jubjubword_corpus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corpus",
            name="words",
        ),
        migrations.AddField(
            model_name="corpus",
            name="filename",
            field=models.CharField(
                default="corpus.txt",
                help_text="Filename in jubjubword directory",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="corpus",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="corpus",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
